import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import os
print(os.getcwd())


ARCHIVO = "Semestral 2024-2.csv"
CARRERA_OBJETIVO = ""           
MATERIA_OBJETIVO = ""

# Semestre 1: ÁLGEBRA, INGLÉS I, LÓGICA, QUÍMICA I, LECTURA, EXPRESIÓN ORAL Y ESCRITA I, TECNOLOGÍAS DE LA INFORMACIÓN Y LA COMUNICACIÓN

# Semestre 2:
# ADMINISTRACIÓN DE RECURSOS HUMANOS:
# DISTINGUE LOS DIFERENTES TIPOS DE EMPRESA POR SU GIRO, ÁREAS FUNCIONALES, DOCUMENTACIÓN ADMINISTRATIVA Y RECURSOS
# ELABORA ESTRATEGIAS PARA REALIZAR LAS ACTIVIDADES DE SU ÁREA
# GEOMETRÍA Y TRIGONOMETRÍA
# INGLÉS II
# LECTURA, EXPRESIÓN ORAL Y ESCRITA II
# MÓDULO I. PLANTEA ACTIVIDADES DEL ÁREA DE RECURSOS HUMANOS EN FUNCIÓN A CADA ÁREA DE LA ORGANIZACIÓN
# QUÍMICA II

# ELECTRICIDAD:
# DISEÑA INSTALACIONES ELÉCTRICAS
# GEOMETRÍA Y TRIGONOMETRÍA
# INGLÉS II
# LECTURA, EXPRESIÓN ORAL Y ESCRITA II
# MÓDULO I. DESARROLLA INSTALACIONES ELÉCTRICAS RESIDENCIALES Y COMERCIALES
# QUÍMICA II
# REALIZA INSTALACIONES ELÉCTRICAS

# PREPARACIÓN DE ALIMENTOS Y BEBIDAS:
# CORTES DE VEGETALES, FRUTAS Y CARNES 
# GEOMETRÍA Y TRIGONOMETRÍA
# INGLÉS II
# LECTURA, EXPRESIÓN ORAL Y ESCRITA II
# MANEJO DE NORMAS DE HIGIENE Y SEGURIDAD EN LA PREPARACIÓN DE ALIMENTOS Y BEBIDAS
# MÓDULO I. PREPARA BASES CULINARIAS
# PREPARA FONDOS, SALSAS MADRES Y DERIVADAS DE ACUERDO AL RECETARIO BASE
# QUÍMICA II

# PROGRAMACIÓN:
# APLICA ESTRUCTURAS DE CONTROL CON UN LENGUAJE DE PROGRAMACIÓN
# APLICA ESTRUCTURAS DE DATOS CON UN LENGUAJE DE PROGRAMACIÓN
# CONSTRUYE ALGORITMOS PARA LA SOLUCIÓN DE PROBLEMAS
# GEOMETRÍA Y TRIGONOMETRÍA
# INGLÉS II
# LECTURA, EXPRESIÓN ORAL Y ESCRITA II
# MÓDULO I. DESARROLLA SOFTWARE DE APLICACIÓN CON PROGRAMACIÓN ESTRUCTURADA
# QUÍMICA II

# Semestre 3:
# ADMINISTRACIÓN DE RECURSOS HUMANOS:
# BIOLOGÍA
# CONTRIBUYE A LA INTEGRACIÓN Y DESARROLLO DEL PERSONAL EN LA ORGANIZACIÓN
# ÉTICA
# GEOMETRÍA ANALÍTICA
# INGLÉS III
# MÓDULO II. INTEGRA EL CAPITAL HUMANO A LA ORGANIZACIÓN
# REALIZA EL PROCESO DE ADMISIÓN Y EMPLEO

# ELECTRICIDAD:
# BIOLOGÍA
# ÉTICA
# GEOMETRÍA ANALÍTICA
# INGLÉS III
# MANTIENE LOS GENERADORES DE CA Y CC
# MANTIENE LOS MOTORES DE CA Y CC
# MÓDULO II. MANTIENE LOS MOTORES Y GENERADORES DE CA Y CC

# PREPARACIÓN DE ALIMENTOS Y BEBIDAS:
# BIOLOGÍA
# ÉTICA
# GEOMETRÍA ANALÍTICA
# INGLÉS III
# MÓDULO II. PREPARA ALIMENTOS DE ACUERDO AL RECETARIO BASE
# PREPARA ENTRADAS Y SOPAS DE ACUERDO A LA RECETA ESTÁNDAR
# PREPARA PLATILLOS REPRESENTATIVOS DE LA COCINA INTERNACIONAL
# PREPARA PLATILLOS REPRESENTATIVOS DE LA COCINA MEXICANA

# PROGRAMACIÓN:
# APLICA LA METODOLOGÍA DE DESARROLLO RÁPIDO DE APLICACIONES CON PROGRAMACIÓN ORIENTADA A EVENTOS
# APLICA LA METODOLOGÍA ESPIRAL CON PROGRAMACIÓN ORIENTADA A OBJETOS
# BIOLOGÍA
# ÉTICA
# GEOMETRÍA ANALÍTICA
# INGLÉS III
# MÓDULO II. APLICA METODOLOGÍAS DE DESARROLLO DE SOFTWARE CON HERRAMIENTAS DE PROGRAMACIÓN VISUAL

# Semestre 4:
# ADMINISTRACIÓN DE RECURSOS HUMANOS:
# ASISTE EN LAS ACTIVIDADES DE CAPACITACIÓN PARA EL DESARROLLO DEL CAPITAL HUMANO
# CÁLCULO DIFERENCIAL
# ECOLOGÍA
# EVALÚA EL DESEMPEÑO DE LA ORGANIZACIÓN UTILIZANDO HERRAMIENTAS DE CALIDAD
# FÍSICA I
# INGLÉS IV
# MÓDULO III. ASISTE EN EL CONTROL Y EVALUACIÓN DEL DESEMPEÑO DEL CAPITAL HUMANO DE LA ORGANIZACIÓN

# ELECTRICIDAD:
# CÁLCULO DIFERENCIAL
# ECOLOGÍA
# FÍSICA I
# INGLÉS IV
# MANTIENE EN OPERACIÓN CIRCUITOS DE CONTROL ELECTROMAGNÉTICO
# MANTIENE EN OPERACIÓN CIRCUITOS DE CONTROL ELECTRÓNICO
# MÓDULO III. MANTIENE EN OPERACIÓN LOS CIRCUITOS DE CONTROL ELECTROMAGNÉTICO Y ELECTRÓNICO
# PROGRAMA Y CONECTA CONTROLADORES LÓGICOS PROGRAMABLES (PLC´S)

# PREPARACIÓN DE ALIMENTOS Y BEBIDAS:
# CÁLCULO DIFERENCIAL
# ECOLOGÍA
# FÍSICA I
# INGLÉS IV
# MÓDULO III. PREPARA PRODUCTOS DE PANADERÍA Y REPOSTERÍA
# PREPARA PRODUCTOS DE PANADERÍA DE ACUERDO AL RECETARIO BASE
# PREPARA PRODUCTOS DE REPOSTERÍA DE ACUERDO AL RECETARIO BASE

# PROGRAMACIÓN:
# CÁLCULO DIFERENCIAL
# CONSTRUYE PÁGINAS WEB
# DESARROLLA APLICACIONES QUE SE EJECUTAN EN EL CLIENTE
# DESARROLLA APLICACIONES QUE SE EJECUTAN EN EL SERVIDOR
# ECOLOGÍA
# FÍSICA I
# INGLÉS IV
# MÓDULO III. DESARROLLA APLICACIONES WEB

# Semestre 5:
# ADMINISTRACIÓN DE RECURSOS HUMANOS:
# CÁLCULO INTEGRAL
# CIENCIA, TECNOLOGÍA, SOCIEDAD Y VALORES
# FÍSICA II
# INGLÉS V
# MÓDULO IV. CONTROLA LOS PROCESOS Y SERVICIOS DE HIGIENE Y SEGURIDAD DEL CAPITAL HUMANO EN LA ORGANIZACIÓN
# SUPERVISA EL CUMPLIMIENTO DE LAS MEDIDAS DE HIGIENE Y SEGURIDAD EN LA ORGANIZACIÓN
# SUPERVISA EL CUMPLIMIENTO DE TAREAS Y PROCESOS PARA EVALUAR LA PRODUCTIVIDAD EN LA ORGANIZACIÓN

# ELECTRICIDAD:
# CÁLCULO INTEGRAL
# CIENCIA, TECNOLOGÍA, SOCIEDAD Y VALORES
# DISEÑA Y MANTIENE LOS SISTEMAS DE ILUMINACIÓN
# FÍSICA II
# IMPLEMENTA Y MANTIENE LOS SISTEMAS DE ENERGÍA RENOVABLE
# INGLÉS V
# MÓDULO IV. DISEÑA Y MANTIENE LOS SISTEMAS DE ILUMINACIÓN Y DE ENERGÍA RENOVABLE
# REALIZA MANTENIMIENTO A LAS INSTALACIONES ELÉCTRICAS RESIDENCIALES, COMERCIALES E INDUSTRIALES

# PREPARACIÓN DE ALIMENTOS Y BEBIDAS:
# CÁLCULO INTEGRAL
# CIENCIA, TECNOLOGÍA, SOCIEDAD Y VALORES
# FÍSICA II
# INGLÉS V
# MÓDULO IV. SIRVE AL COMENSAL SEGÚN ESTÁNDARES DE LA EMPRESA
# MONTA MESAS DE ACUERDO AL TIPO DE SERVICIO
# SIRVE ALIMENTOS Y BEBIDAS

# PROGRAMACIÓN:
# CÁLCULO INTEGRAL
# CIENCIA, TECNOLOGÍA, SOCIEDAD Y VALORES
# CONSTRUYE BASES DE DATOS PARA APLICACIONES WEB
# DESARROLLA APLICACIONES WEB CON CONEXIÓN A BASES DE DATOS
# FÍSICA II
# INGLÉS V
# MÓDULO IV. DESARROLLA SOFTWARE DE APLICACIÓN WEB CON ALMACENAMIENTO PERSISTENTE DE DATOS

# Semestre 6:
# ADMINISTRACIÓN DE RECURSOS HUMANOS:
# DETERMINA LA NÓMINA DEL PERSONAL DE LA ORGANIZACIÓN TOMANDO EN CUENTA LA NORMATIVIDAD LABORAL
# DETERMINA REMUNERACIONES DEL PERSONAL EN SITUACIONES EXTRAORDINARIAS
# INTRODUCCIÓN A LA ECONOMÍA
# INTRODUCCIÓN AL DERECHO
# MÓDULO V. DETERMINA LAS REMUNERACIONES AL CAPITAL HUMANO DE LA ORGANIZACIÓN
# PROBABILIDAD Y ESTADÍSTICA
# TEMAS DE FILOSOFÍA

# ELECTRICIDAD:
# MATEMÁTICAS APLICADAS
# MÓDULO V. MANTIENE INSTALACIONES ELÉCTRICAS DE MEDIA Y BAJA TENSIÓN
# PROBABILIDAD Y ESTADÍSTICA
# REALIZA MANTENIMIENTO EN EL SISTEMA DE DISTRIBUCIÓN DE ENERGÍA ELÉCTRICA
# REALIZA MANTENIMIENTO EN SUBESTACIONES ELÉCTRICAS
# TEMAS DE FILOSOFÍA
# TEMAS DE FÍSICA

# PREPARACIÓN DE ALIMENTOS Y BEBIDAS:
# INTRODUCCIÓN A LA ECONOMÍA
# MÓDULO V. PREPARA BEBIDAS ALCOHÓLICAS Y NO ALCOHÓLICAS
# ORIGEN Y CLASIFICACIÓN DE LAS BEBIDAS
# PREPARA BEBIDAS Y COCTELES DE ACUERDO AL RECETARIO BASE
# PROBABILIDAD Y ESTADÍSTICA
# TEMAS DE ADMINISTRACIÓN
# TEMAS DE FILOSOFÍA

# PROGRAMACIÓN:
# DESARROLLA APLICACIONES MÓVILES PARA ANDROID
# DESARROLLA APLICACIONES MÓVILES PARA IOS
# MATEMÁTICAS APLICADAS
# MÓDULO V. DESARROLLA APLICACIONES PARA DISPOSITIVOS MÓVILES
# PROBABILIDAD Y ESTADÍSTICA
# TEMAS DE FILOSOFÍA
# TEMAS DE FÍSICA

df = pd.read_csv(ARCHIVO, encoding="utf-8")

df["DESERTO"] = (
    df["DESERTO"].astype(str).str.strip().str.upper().map({"SI": 1, "NO": 0})
)

mask_carrera = df["CARRERA"].astype(str).str.strip() == CARRERA_OBJETIVO
df_carrera = df.loc[mask_carrera].copy()

mask_materia = df_carrera["NOMBRE ASIGNATURA"].astype(str).str.strip() == MATERIA_OBJETIVO
df_materia = df_carrera.loc[mask_materia].copy()

cal_cols  = ["PARCIAL 1","PARCIAL 2","PARCIAL 3","CALIFICACION"]
asis_cols = ["ASISTENCIAS 1","ASISTENCIAS 2","ASISTENCIAS 3","TOTAL ASISTENCIAS"]

for c in cal_cols + asis_cols:
    if c in df_materia.columns:
        df_materia[c] = pd.to_numeric(df_materia[c], errors="coerce")

columnas = [c for c in cal_cols + asis_cols if c in df_materia.columns] + ["DESERTO"]
corr = df_materia[columnas].corr(method="spearman").fillna(0)

print("\nCorrelación con DESERTO:")
print(corr["DESERTO"].sort_values(ascending=False))

plt.figure(figsize=(10, 6))
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f", linewidth=.5, square=True)
plt.title(f"Semestre 6 | {CARRERA_OBJETIVO} | {MATERIA_OBJETIVO}", fontsize=14)
plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()